tmp: ./tmp

app: src
dest: dist




modules_external_deps:
  github/oauthio: oauthio
  spinner: spinner
  template: handlebars

default: small
builds:
  small:
    filename: radic.small
    modules: [ base, core ]
    lodash: [ omit, pick, values, keys, where, cloneDeep, isUndefined ]
  all:
    filename: radic.all
    modules: [ base, core,
              async/waterfall, async/each, cookie, crypt, github, github/oauthio, github/sync, json, # sdf
              spinner, sprintf, storage, template, template/general, template/comparisons, widgets, widgets/base, wordwrap,
              exports/amd, exports/global ]
    lodash: [ omit, pick, values, keys, where, cloneDeep, isUndefined ]
