tmp: ./tmp

app: src
dest: dist




modules_external_deps:
  github/oauthio: oauthio
  spinner: spinner
  template: handlebars
  widgets: widgetfactory

default: small
builds:
  small:
    filename: radic.small
    modules: [ base, core ]
    lodash: [ omit, pick, values, keys, where, cloneDeep, isUndefined, isNumber, isBoolean, isNull, isDate, toArray ]
  all:
    filename: radic.all
    modules: [ base, core,
              async/waterfall, async/each, cookie, crypt/md5, crypt/utf8, github, github/oauthio, github/sync, json, # sdf
              spinner, sprintf, storage, template, template/general, template/comparisons, widgets, wordwrap,
              exports/amd, exports/global ]
    lodash: [ omit, pick, values, keys, where, cloneDeep, isUndefined, isNumber, isBoolean, isNull, isDate, toArray ]
  githubio:
    filename: radic.githubio
    ignoredeps: [ github/oauthio, widgets ]
    modules: [ base, core,
              async/waterfall, async/each, cookie, crypt/md5, crypt/utf8, github, github/oauthio, github/sync, json,
              spinner, storage, template, template/general, template/comparisons, widgets, wordwrap,
              exports/amd, exports/global ]
    lodash: [ omit, pick, values, keys, where, cloneDeep, isUndefined, isNumber, isBoolean, isNull, isDate, toArray ]
  githubprofile:
    filename: radic.githubprofile
    ignoredeps: [ github/oauthio ]
    modules: [ base, core, github,
              spinner, template, template/general, widgets,
              exports/amd, exports/global ]
    lodash: [ omit, pick, values, keys, where, cloneDeep, isUndefined, isNumber, isBoolean, isNull, isDate, toArray ]
